theme: jekyll-theme-minimal
title: [Viola Campos]
description: [I am a developer especially interested in Machine Learning, NLP and Computer Vision. Currently I am writing my Masters Thesis about Retrieval-Augmented Language Models.]
logo: /assets/viola_small.jpg
show_downloads: false

